### ISSUE TITLE
PPV_diff の計算がおかしい？

### ISSUE THREAD

**Issue by KoyoKawano** [CI-labo-OPU/MoFGBML#16]
https://github.com/CI-labo-OPU/MoFGBML/blob/812b55f67a6a4c7d58ffa745da3fc7e4647b129f/src/cilabo/metric/fairness/PositivePredictiveValuesDifference.java#L53-L57
でy^=0のパターンのみ次の処理が行われる．

https://github.com/CI-labo-OPU/MoFGBML/blob/812b55f67a6a4c7d58ffa745da3fc7e4647b129f/src/cilabo/metric/fairness/PositivePredictiveValuesDifference.java#L69-L72
ではy^ = 0のパターンのみ対して処理が行われる．しかし，前述の処理により，y^ = 0のパターンのみしかこの条件式に到達しないので，
https://github.com/CI-labo-OPU/MoFGBML/blob/812b55f67a6a4c7d58ffa745da3fc7e4647b129f/src/cilabo/metric/fairness/PositivePredictiveValuesDifference.java#L71
の処理は行われない．最後にPPV_diffの分子はこのカウントなので，PPV_diffは常に0になっている．

**Comment by onikUone** [comment]
@KoyoKawano 
issue立ててくれてありがとう！

https://github.com/CI-labo-OPU/MoFGBML/blob/812b55f67a6a4c7d58ffa745da3fc7e4647b129f/src/cilabo/metric/fairness/PositivePredictiveValuesDifference.java#L53-L57
に関してだけど、
y^ = 0のパターンは55行目の条件を満たすから、このif文に入って、continueで次のループにジャンプするはず。
59行目以降は、y^=1のパターンに対してのみ実行されると思う。

でも、条件式を評価する回数は一緒でcontinueを使ってパターンをはじくみたいなややこしい実装はなくした方が良いかもしれない。
言ってくれたように、分子を`y=1 & y^=1 & a=0`の条件でインクリメントして、分母は`y^=1 & a=0`の条件でインクリメントするようなシンプルなコードの方が良い気がした。

https://github.com/CI-labo-OPU/MoFGBML/blob/812b55f67a6a4c7d58ffa745da3fc7e4647b129f/src/cilabo/metric/fairness/PositivePredictiveValuesDifference.java#L47-L73
47行目から73行目までのforループの部分を次のように変更するのはどうかな？
下にもコード書いたけど、差分を見やすいようにプルリクエストも送っておきます．#18

```java {.line-number}
		for(int p = 0; p < size; p++) {
			FairnessPattern pattern = (FairnessPattern)dataset.getPattern(p);
			ClassLabel trueClass = pattern.getTrueClass();
			// Classification
			ClassLabel classifiedClass = classifier.classify(pattern.getInputVector()).getConsequent().getClassLabel();

			// Rejected ならば 次のパターン
			if(classifiedClass.getClass() == RejectedClassLabel.class) {
				continue;
			}

			// Sensitive attribute value
			int a = pattern.getA();

			//分母
			if(classifiedClass.getClassLabel() == 1) {
				sizeForSensitive[a]++;

				//分子
				if(trueClass.getClassLabel() == 1) {
					countForSensitive[a]++;
				}
			}
		}
```
